on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

name: Setup universes

jobs:
  update:
    name: Check for new app installations
    runs-on: ubuntu-20.04
    steps:
      - name: Scrape CRAN descriptions
        uses: r-universe-org/setup-universes@master
        env:
          GH_APP_KEY: ${{ secrets.GH_APP_KEY }}
